# -*- coding: utf-8 -*-
"""COVID_pdfReader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f01pO40x5qjeZvP2Y9jOmh6J8WYAVmRb
"""

!pip install slate3k
!pip install pygsheets

from google.colab import drive
drive.mount('/content/drive')

import glob

path = '/content/drive/My Drive/Upload your Isabel Symptom Checker results here. (File responses)/'
files= glob.glob(path + '/*.pdf')

files

import google.auth
from google.colab import auth

auth.authenticate_user()
import pygsheets
credentials, _ = google.auth.default()
gc = pygsheets.client.Client(credentials)

key = '1T_1DbRRnZ6ZIYWwJeS_ojqa-6CZWCDs7u0jCsKR3YjY'
sheet = gc.open_by_key(key) 

worksheet = sheet.worksheet_by_title('Form Responses 1')

import slate3k as slt

# text extractor function
def text_extractor(file):
    report_id = open(file, 'rb')
    raw_text = (slt.PDF(report_id)) # raw data
    report_id.close()
    stage_1 = raw_text[0].split('\n') # stage 1 of cleaning
    stage_2 = (list(dict.fromkeys(stage_1))) # stage 2 of cleaning
    stage_2.remove('')

    if 'Contact Details' in stage_2:
        stage_2.remove(stage_2[stage_2.index('Contact Details')+1])
        stage_2.remove(stage_2[stage_2.index('Name')+1])
        stage_2.remove(stage_2[stage_2.index('Any additional information which you think is relevant')+1])


    # stage 3 of cleaning
    age = stage_2[stage_2.index('Age')+1]
    gender = stage_2[stage_2.index('Gender')+1]
    country = stage_2[stage_2.index('Country')+1]
    raw_sym = [k for k in stage_2 if k.lower()==k]
    unwanted = {'', 'Common', 'common', ' ', '  ', '\x0c', 'Symptoms entered', 'Show AllAll', 'Show ', 'Red Flag',
                'Red ', 'Flag', 'Your results', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'}
    raw_sym_2 = [h for h in raw_sym if h not in unwanted]
    symptoms = (' '.join(raw_sym_2)).split(',')
    if 'Pregnancy' in stage_2:
        pregnancy = stage_2[stage_2.index('Pregnancy')+1]
    else:
        pregnancy = 'Not Applicable'
    try:
        raw_dis = stage_2[stage_2.index('Your results'):]
    except:
        raw_dis = stage_2[stage_2.index('Show AllAll'):]
    raw_dis_2 = [e for e in raw_dis if e not in unwanted]
    diseases =[b.strip() for b in raw_dis_2]

    return age, gender, country, pregnancy, symptoms, diseases

count = 2
for file in files:
  try:
    age, gender, country, pregnancy, symptoms, diseases = text_extractor(file)

    print('Age:', age)
    print('Gender:', gender)
    print('Symptoms:', symptoms)
    try:
      print('Diseases:', diseases[0:10])
    except:
      print('Diseases:', diseases)

    worksheet.update_value('D'+ str(count), str(age))
    worksheet.update_value('E' + str(count), gender)  
    worksheet.update_value('F' + str(count), country) 
    worksheet.update_value('G' + str(count), ",".join(symptoms)) 
    worksheet.update_value('H' + str(count), ",".join(diseases[0:10]))
  except:
    print('Did not work for file: ' + file)
  count += 1